### ISSUE TITLE
YayaSite - IE 11 broken view

### ISSUE THREAD

**Issue by simon-sh** [yayasoft/ytour#174]
There is a problem with YayaSoft site in Internet Explorer 11.

Please review the attached screenshot.

![5](https://cloud.githubusercontent.com/assets/8789505/5129059/ec72ab34-70e7-11e4-9564-5f9d0d398806.PNG)

Please notice, at the front page 'YVote...' and 'YTour...' boxes are emtpy.
When you hit F5, the text in the boxes appear, but we don't expect random visitors to hit F5 :-)

Avi meet same problme with Opera browser.

With Google Chrome every seems to be OK.

**Comment by web4social** [comment]
This problem occurs **in all browsers**, because of the low-speed connection. With fiddler we simulated low download speed.
So the problem was not in the browser, but the fact that the localization directive **loaded earlier than the language dictionary** have time to get values from http request.
And we did that the dictionary **is already full** before starting our angular application.

**Comment by novice3030** [comment]
Please don't post issue that has to do with yaya site under ytour
If this is fixed please close it
